/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryNetworkAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import userinterface.StateNetworkAdminRole.ManageEnterpriseAdminJPanel;
import userinterface.StateNetworkAdminRole.ManageEnterpriseJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Neha
 */
public class CountryNetworkAdminWorkArea extends javax.swing.JPanel {
      private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    /**
     * Creates new form NetworkAdminWorkArea
     */
      
    public CountryNetworkAdminWorkArea(JPanel userProcessContainer, UserAccount account , EcoSystem system) {
        initComponents();
            this.userProcessContainer = userProcessContainer;
         this.system = system;
         this.account = account;
         populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel treeModel = (DefaultTreeModel) NetworkJTree.getModel();
        ArrayList<Network> networkList = system.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        Network stateNetwork;
        Network cityNetwork;
        
        DefaultMutableTreeNode rootNetwork = new DefaultMutableTreeNode("Network");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)treeModel.getRoot();
        root.removeAllChildren();
        root.insert(rootNetwork,0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode stateNetworkNode;
        DefaultMutableTreeNode cityNetworkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i = 0; i<networkList.size(); i++){
            network = networkList.get(i);
            if(network.getUserAccountDirectory().getUserAccountList().size() > 0){
                if(network.getUserAccountDirectory().getUserAccountList().get(0).getUsername().equals(account.getUsername())){
                 networkNode = new DefaultMutableTreeNode(network.getNetworkName());
                 rootNetwork.insert(networkNode, i);
            
            for(int j = 0 ; j<network.getSubNetwork().size(); j++){
                stateNetwork = network.getSubNetwork().get(j);
                stateNetworkNode = new DefaultMutableTreeNode(stateNetwork.getNetworkName());
                networkNode.insert(stateNetworkNode, j);
                
                
                for(int k = 0; k<stateNetwork.getSubNetwork().size(); k++){
                   cityNetwork = stateNetwork.getSubNetwork().get(k);
                   cityNetworkNode = new DefaultMutableTreeNode(cityNetwork.getNetworkName());
                   stateNetworkNode.insert(cityNetworkNode, k);
                   
                   enterpriseList = cityNetwork.getEnterpriseDirectory().getEnterpriseList();
                   for(int a = 0; a<enterpriseList.size(); a++){
                      enterprise = enterpriseList.get(a);
                      enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                      cityNetworkNode.insert(enterpriseNode, a);
                
                      organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                
                      for(int b = 0; b< organizationList.size(); b++){
                          organization = organizationList.get(b);
                          organizationNode = new DefaultMutableTreeNode(organization.getName());
                          enterpriseNode.insert(organizationNode, b);
                      }
                    } 
                }
            } 
            }
            }
            
                   
        }
        treeModel.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        MngEnterpriseBtn = new javax.swing.JButton();
        MngEnterpriseAdminBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NetworkJTree = new javax.swing.JTree();
        manageRequestsBtn = new javax.swing.JButton();
        manageStateNetworkAdminBtn = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MngEnterpriseBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MngEnterpriseBtn.setText("Manage Enterprise");
        MngEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MngEnterpriseBtnActionPerformed(evt);
            }
        });
        add(MngEnterpriseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 99, 261, 39));

        MngEnterpriseAdminBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MngEnterpriseAdminBtn.setText("Manage Enterprise Admin");
        MngEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MngEnterpriseAdminBtnActionPerformed(evt);
            }
        });
        add(MngEnterpriseAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 192, -1, 42));

        NetworkJTree.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        NetworkJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(NetworkJTree);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 174, 652));

        manageRequestsBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageRequestsBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        manageRequestsBtn.setText("Manage WorkRequests");
        manageRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestsBtnActionPerformed(evt);
            }
        });
        add(manageRequestsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 300, -1));

        manageStateNetworkAdminBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageStateNetworkAdminBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        manageStateNetworkAdminBtn.setText("Manage State Network Admin");
        manageStateNetworkAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStateNetworkAdminBtnActionPerformed(evt);
            }
        });
        add(manageStateNetworkAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void MngEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MngEnterpriseBtnActionPerformed
        ManageEnterpriseJPanel manageEnterprise = new ManageEnterpriseJPanel(userProcessContainer,account, system);
        userProcessContainer.add("ManageEnterpriseJPanel",manageEnterprise);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MngEnterpriseBtnActionPerformed

    private void MngEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MngEnterpriseAdminBtnActionPerformed
        ManageEnterpriseAdminJPanel manageEnterpriseAdmin = new ManageEnterpriseAdminJPanel(userProcessContainer,account, system);
        userProcessContainer.add("ManageEnterpriseAdminJPanel",manageEnterpriseAdmin);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MngEnterpriseAdminBtnActionPerformed

    private void manageRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestsBtnActionPerformed
       
    }//GEN-LAST:event_manageRequestsBtnActionPerformed

    private void manageStateNetworkAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStateNetworkAdminBtnActionPerformed
        ManageStateNetworkAdminJPanl manageNetworkAdmin = new ManageStateNetworkAdminJPanl(userProcessContainer,account, system);
        userProcessContainer.add("ManageNetworkAdminJPanel",manageNetworkAdmin);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStateNetworkAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MngEnterpriseAdminBtn;
    private javax.swing.JButton MngEnterpriseBtn;
    private javax.swing.JTree NetworkJTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton manageRequestsBtn;
    private javax.swing.JButton manageStateNetworkAdminBtn;
    // End of variables declaration//GEN-END:variables
}
