/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LegalRepresentativeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FindDonorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha
 */
public class LegalRepresentativeWorkArea extends javax.swing.JPanel {
private JPanel userProcessContainer;
private UserAccount account;
private Network inNetwork;
private Enterprise enterprise;
private EcoSystem business;

    /**
     * Creates new form LegalRepresentativeWorkArea
     */
    public LegalRepresentativeWorkArea(JPanel userProcessContainer, UserAccount account,Network inNetwork, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.inNetwork=inNetwork;
        this.enterprise=enterprise;
        this.business=business;
        populateWorkQueue();
        cityNameLabel.setText(inNetwork.getNetworkName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        legalWorkRequestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cityNameLabel = new javax.swing.JLabel();
        viewLegalRequestButton = new javax.swing.JButton();

        legalWorkRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Hospital ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(legalWorkRequestTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Legal Department Work Area");

        cityNameLabel.setText("<< City name >>");

        viewLegalRequestButton.setText("View Request >>");
        viewLegalRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLegalRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(cityNameLabel)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(viewLegalRequestButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cityNameLabel))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(viewLegalRequestButton)
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewLegalRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLegalRequestButtonActionPerformed
        
        int selectedRow= legalWorkRequestTable.getSelectedRow();
        if (selectedRow>=0)
        {
        FindDonorRequest request= (FindDonorRequest)legalWorkRequestTable.getValueAt(selectedRow, 0);
        ViewLegalRequestPanel viewLegalRequestPanel = new ViewLegalRequestPanel(userProcessContainer,request);
        userProcessContainer.add("viewLegalRequestPanel", viewLegalRequestPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            
            JOptionPane.showMessageDialog(this, "Please select a row", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewLegalRequestButtonActionPerformed
    public void populateWorkQueue(){
        
        DefaultTableModel model = (DefaultTableModel) legalWorkRequestTable.getModel();
        model.setRowCount(0);
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = ((FindDonorRequest) request).getHospitalID();
            String result = ((FindDonorRequest) request).getAuthorization();
            row[2] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable legalWorkRequestTable;
    private javax.swing.JButton viewLegalRequestButton;
    // End of variables declaration//GEN-END:variables
}
