/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OPTDAdminRole;

/**
 *
 * @author Neha
 */
public class OPTDAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form OPTDAdminWorkArea
     */
    public OPTDAdminWorkArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("OPTD ADMIN WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jButton1.setText("Manage Organ Matching>>");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 330, -1));

        jButton2.setText("Manage Organ Procurement and Transplantation >>");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jButton3.setText("Manage Employees>>");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 330, -1));

        jButton4.setText("Manage Users>>");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 330, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
