/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.Patient;
import Business.Network.Network;
import Business.Organization.Hospital.HospitalRepOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FindDonorRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neha
 */
public class RaiseNewRequestPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private UserAccount userAccount;

    /**
     * Creates new form RaiseNewRequestPanel
     */
    public RaiseNewRequestPanel(JPanel userProcessContainer,UserAccount userAccount,Network cityNetwork, EcoSystem system) {
        initComponents();
        this.system = system;
        this.network = cityNetwork;
        this.userProcessContainer = userProcessContainer;
        this.userAccount= userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderLabel = new javax.swing.JLabel();
        patientidlabel = new javax.swing.JLabel();
        patientnamelabel = new javax.swing.JLabel();
        OrganNeededLabel = new javax.swing.JLabel();
        patientagelabel = new javax.swing.JLabel();
        PatientBloodTypeLabel = new javax.swing.JLabel();
        PatientWeightLabel = new javax.swing.JLabel();
        OrganSizeLabel = new javax.swing.JLabel();
        PatientIDTextField = new javax.swing.JTextField();
        PatientNameField = new javax.swing.JTextField();
        PatientAgeTextField = new javax.swing.JTextField();
        PatientBloodTypeTextField = new javax.swing.JTextField();
        PatientWeightTextField = new javax.swing.JTextField();
        OrganNeededTextField = new javax.swing.JTextField();
        OrganSizeTextField = new javax.swing.JTextField();
        RaiseRequestBtn = new javax.swing.JButton();
        MedicalCondLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OtherMedicalConditionTextArea = new javax.swing.JTextArea();
        BackBtn = new javax.swing.JButton();
        patientContactNoLabel = new javax.swing.JLabel();
        ContactNoTextField = new javax.swing.JTextField();
        HospitalContactNoLabel = new javax.swing.JLabel();
        HospitalContactNoTextField = new javax.swing.JTextField();
        CriticalLabel = new javax.swing.JLabel();
        CriticalTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderLabel.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        HeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel.setText("Raise Donor Requirement request");
        add(HeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 42, 434, -1));

        patientidlabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientidlabel.setText("Patient ID:");
        add(patientidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 102, -1, -1));

        patientnamelabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientnamelabel.setText("Patient Name:");
        add(patientnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 151, -1, -1));

        OrganNeededLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        OrganNeededLabel.setText("Organ affected:");
        add(OrganNeededLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        patientagelabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientagelabel.setText("Age:");
        add(patientagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 200, -1, -1));

        PatientBloodTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PatientBloodTypeLabel.setText("Blood type:");
        add(PatientBloodTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        PatientWeightLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PatientWeightLabel.setText("Body Weight:");
        add(PatientWeightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        OrganSizeLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        OrganSizeLabel.setText("Organ size:");
        add(OrganSizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        PatientIDTextField.setEditable(false);
        PatientIDTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(PatientIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 99, 166, -1));

        PatientNameField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(PatientNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 148, 166, -1));

        PatientAgeTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PatientAgeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAgeTextFieldActionPerformed(evt);
            }
        });
        add(PatientAgeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 197, 166, -1));

        PatientBloodTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(PatientBloodTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 166, -1));

        PatientWeightTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(PatientWeightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 166, -1));

        OrganNeededTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(OrganNeededTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 166, -1));

        OrganSizeTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(OrganSizeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 166, -1));

        RaiseRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RaiseRequestBtn.setText("Raise request");
        RaiseRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaiseRequestBtnActionPerformed(evt);
            }
        });
        add(RaiseRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 768, 207, -1));

        MedicalCondLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MedicalCondLabel.setText("Other Medical Conditions:");
        add(MedicalCondLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        OtherMedicalConditionTextArea.setColumns(20);
        OtherMedicalConditionTextArea.setRows(5);
        jScrollPane1.setViewportView(OtherMedicalConditionTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 260, 66));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BackBtn.setText("<< Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 742, -1, -1));

        patientContactNoLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientContactNoLabel.setText("Contact Number :");
        add(patientContactNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        ContactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(ContactNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 166, 34));

        HospitalContactNoLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        HospitalContactNoLabel.setText("Hospital Contact Number : ");
        add(HospitalContactNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, -1, -1));

        HospitalContactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        HospitalContactNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalContactNoTextFieldActionPerformed(evt);
            }
        });
        add(HospitalContactNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 169, 34));

        CriticalLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        CriticalLabel.setText("Criticality : ");
        add(CriticalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 226, 26));
        add(CriticalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 666, 169, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void RaiseRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaiseRequestBtnActionPerformed
       Patient patient = null;
       int hospitalID = 0;
       String hospitalName = null;
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)){
                hospitalID = enterprise.getEnterpriseID();
                hospitalName = enterprise.getName();
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(organization instanceof HospitalRepOrganization){
                       patient = ((HospitalRepOrganization) organization).getPatientDirectory().getPatient();
                    }
                }
            }
        }
        
        patient.setPatientName(PatientNameField.getText());
        patient.setPatientAge(Integer.parseInt(PatientAgeTextField.getText()));
        patient.setPatientLocation(network.getNetworkName());
        patient.setBloodType(PatientBloodTypeTextField.getText());
        patient.setWeight(Double.parseDouble(PatientWeightTextField.getText()));
        patient.setOrganNeeded(OrganNeededTextField.getText());
        patient.setOrganSize(Integer.parseInt(OrganSizeTextField.getText()));
        patient.setOtherMedicalCondition(OtherMedicalConditionTextArea.getText());
        patient.setPatientContactNumber(Integer.parseInt(patientContactNoLabel.getText()));
        patient.setCritical(CriticalTextField.getText());
        
        FindDonorRequest findDonorReq = new FindDonorRequest();
        findDonorReq.setPatientDetails(patient);
        findDonorReq.setSender(userAccount);
        findDonorReq.setStatus("Request Raised");
        findDonorReq.setRequestDate(new Date());
        findDonorReq.setHospitalID(hospitalID);
        findDonorReq.setHospitalName(hospitalName);
        findDonorReq.setHospitalAddress(network.getNetworkName());
        findDonorReq.setHospitalContactNo(Integer.parseInt(HospitalContactNoTextField.getText()));
        
        for(Network network : system.getNetworkList()){
            for(Network stateNetwork : network.getSubNetwork()){
                for(Network cityNetwork : stateNetwork.getSubNetwork()){
                    if(cityNetwork.getNetworkName().equals(this.network.getNetworkName())){
                        stateNetwork.getWorkQueue().getWorkRequestList().add(findDonorReq);
                        JOptionPane.showMessageDialog(null, "Request raised successfully");
                    }
                }
            }
        }
        userAccount.getWorkQueue().getWorkRequestList().add(findDonorReq);

    }//GEN-LAST:event_RaiseRequestBtnActionPerformed

    private void PatientAgeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAgeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientAgeTextFieldActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RaiseAndViewMyRequests viewRequest = (RaiseAndViewMyRequests) component;
        viewRequest.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void HospitalContactNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalContactNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalContactNoTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField ContactNoTextField;
    private javax.swing.JLabel CriticalLabel;
    private javax.swing.JTextField CriticalTextField;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JLabel HospitalContactNoLabel;
    private javax.swing.JTextField HospitalContactNoTextField;
    private javax.swing.JLabel MedicalCondLabel;
    private javax.swing.JLabel OrganNeededLabel;
    private javax.swing.JTextField OrganNeededTextField;
    private javax.swing.JLabel OrganSizeLabel;
    private javax.swing.JTextField OrganSizeTextField;
    private javax.swing.JTextArea OtherMedicalConditionTextArea;
    private javax.swing.JTextField PatientAgeTextField;
    private javax.swing.JLabel PatientBloodTypeLabel;
    private javax.swing.JTextField PatientBloodTypeTextField;
    private javax.swing.JTextField PatientIDTextField;
    private javax.swing.JTextField PatientNameField;
    private javax.swing.JLabel PatientWeightLabel;
    private javax.swing.JTextField PatientWeightTextField;
    private javax.swing.JButton RaiseRequestBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patientContactNoLabel;
    private javax.swing.JLabel patientagelabel;
    private javax.swing.JLabel patientidlabel;
    private javax.swing.JLabel patientnamelabel;
    // End of variables declaration//GEN-END:variables
}
