/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateNetworkAdminRole;

import Business.EcoSystem;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FindDonorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ApoorvaLakhmani
 */
public class StateNetworkManageRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    private Network stateNetwork;
    /**
     * Creates new form StateNetworkManageRequestJPanel
     */
    StateNetworkManageRequestJPanel(JPanel userProcessContainer, UserAccount account, Network stateNetwork,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.stateNetwork = stateNetwork;
        
        populatetable();
    }
    
    public void populatetable(){
        DonorRequestTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 20));
        DefaultTableModel model = (DefaultTableModel) DonorRequestTable.getModel();
        model.setRowCount(0);
        
        for(Network countryNetwork : system.getNetworkList()){
            for(Network stateNetwork : countryNetwork.getSubNetwork()){
                if(stateNetwork.getNetworkName().equals(this.stateNetwork.getNetworkName())){
                    for(WorkRequest request : stateNetwork.getWorkQueue().getWorkRequestList()){
                        FindDonorRequest donorReq = (FindDonorRequest) request;
                        Object[] row = new Object[3];
                        row[0] = request;
                        row[1] = donorReq.getPatientDetails().getPatientID();
                        row[2] = request.getStatus();
                        
                        model.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DonorRequestTable = new javax.swing.JTable();
        ViewRequestBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DonorRequestTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DonorRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RequestID", "HospitalID", "Status"
            }
        ));
        jScrollPane1.setViewportView(DonorRequestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 90, 638, 164));

        ViewRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ViewRequestBtn.setText("View Request");
        ViewRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRequestBtnActionPerformed(evt);
            }
        });
        add(ViewRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 240, 50));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BackBtn.setText("<< Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 170, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRequestBtnActionPerformed
        
        int selectedRow= DonorRequestTable.getSelectedRow();
        if(selectedRow >= 0){
            FindDonorRequest request= (FindDonorRequest)DonorRequestTable.getValueAt(selectedRow, 0);
            ViewDonorRequestJPanel viewDonorReq = new ViewDonorRequestJPanel(userProcessContainer,account,stateNetwork,system,request);
            userProcessContainer.add("ViewDonorRequestJPanel",viewDonorReq);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Select an element");
        }
        
        
        
    }//GEN-LAST:event_ViewRequestBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTable DonorRequestTable;
    private javax.swing.JButton ViewRequestBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
