/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateNetworkAdminRole;

import Business.EcoSystem;
import Business.Network.Network;
import Business.RegCenter.Donor;
import Business.RegCenter.Organ;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FindDonorRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author ApoorvaLakhmani
 */
public class ViewDonorRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    private Network stateNetwork;
    private FindDonorRequest request;
    /**
     * Creates new form ViewDonorRequestJPanel
     */
    public ViewDonorRequestJPanel(JPanel userProcessContainer, UserAccount account, Network stateNetwork,EcoSystem system,FindDonorRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.stateNetwork = stateNetwork;
        this.request = request;
        
        populateData();
    }
    
    public void populateData(){
        PatientIDTextField.setText(String.valueOf(request.getPatientDetails().getPatientID()));
        PatientNameField.setText(request.getPatientDetails().getPatientName());
        PatientAgeTextField.setText(String.valueOf(request.getPatientDetails().getPatientAge()));
        PatientLocTextField.setText(request.getPatientDetails().getPatientLocation());
        ContactNoTextField.setText(String.valueOf(request.getPatientDetails().getPatientContactNumber()));
        PatientBloodTypeTextField.setText(request.getPatientDetails().getBloodType());
        PatientWeightTextField.setText(String.valueOf(request.getPatientDetails().getWeight()));
        OrganNeededTextField.setText(request.getPatientDetails().getOrganNeeded());
        OrganSizeTextField.setText(String.valueOf(request.getPatientDetails().getOrganSize()));
        OtherMedicalConditionTextArea.setText(request.getPatientDetails().getOtherMedicalCondition());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FindDonorBtn = new javax.swing.JButton();
        OrganSizeTextField = new javax.swing.JTextField();
        PatientLocLabel = new javax.swing.JLabel();
        PatientLocTextField = new javax.swing.JTextField();
        MedicalCondLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OtherMedicalConditionTextArea = new javax.swing.JTextArea();
        patientContactNoLabel = new javax.swing.JLabel();
        patientidlabel = new javax.swing.JLabel();
        ContactNoTextField = new javax.swing.JTextField();
        patientnamelabel = new javax.swing.JLabel();
        OrganNeededLabel = new javax.swing.JLabel();
        patientagelabel = new javax.swing.JLabel();
        PatientBloodTypeLabel = new javax.swing.JLabel();
        PatientWeightLabel = new javax.swing.JLabel();
        OrganSizeLabel = new javax.swing.JLabel();
        PatientIDTextField = new javax.swing.JTextField();
        PatientNameField = new javax.swing.JTextField();
        PatientAgeTextField = new javax.swing.JTextField();
        PatientBloodTypeTextField = new javax.swing.JTextField();
        PatientWeightTextField = new javax.swing.JTextField();
        OrganNeededTextField = new javax.swing.JTextField();

        FindDonorBtn.setText("Find Donor");
        FindDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindDonorBtnActionPerformed(evt);
            }
        });

        OrganSizeTextField.setEditable(false);
        OrganSizeTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        PatientLocLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PatientLocLabel.setText("Location:");

        PatientLocTextField.setEditable(false);
        PatientLocTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        MedicalCondLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MedicalCondLabel.setText("Other Medical Conditions:");

        OtherMedicalConditionTextArea.setEditable(false);
        OtherMedicalConditionTextArea.setColumns(20);
        OtherMedicalConditionTextArea.setRows(5);
        jScrollPane1.setViewportView(OtherMedicalConditionTextArea);

        patientContactNoLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientContactNoLabel.setText("Contact Number :");

        patientidlabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientidlabel.setText("Patient ID:");

        ContactNoTextField.setEditable(false);
        ContactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        patientnamelabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientnamelabel.setText("Patient Name:");

        OrganNeededLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        OrganNeededLabel.setText("Organ affected:");

        patientagelabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        patientagelabel.setText("Age:");

        PatientBloodTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PatientBloodTypeLabel.setText("Blood type:");

        PatientWeightLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PatientWeightLabel.setText("Body Weight:");

        OrganSizeLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        OrganSizeLabel.setText("Organ size:");

        PatientIDTextField.setEditable(false);
        PatientIDTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        PatientNameField.setEditable(false);
        PatientNameField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        PatientAgeTextField.setEditable(false);
        PatientAgeTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PatientAgeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAgeTextFieldActionPerformed(evt);
            }
        });

        PatientBloodTypeTextField.setEditable(false);
        PatientBloodTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        PatientWeightTextField.setEditable(false);
        PatientWeightTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        OrganNeededTextField.setEditable(false);
        OrganNeededTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientidlabel)
                            .addComponent(patientnamelabel)
                            .addComponent(patientagelabel)
                            .addComponent(PatientLocLabel)
                            .addComponent(patientContactNoLabel)
                            .addComponent(PatientBloodTypeLabel)
                            .addComponent(PatientWeightLabel)
                            .addComponent(OrganNeededLabel)
                            .addComponent(OrganSizeLabel)
                            .addComponent(MedicalCondLabel))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PatientLocTextField)
                                .addComponent(PatientAgeTextField)
                                .addComponent(PatientNameField)
                                .addComponent(PatientIDTextField)
                                .addComponent(ContactNoTextField)
                                .addComponent(PatientBloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PatientWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OrganNeededTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OrganSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(FindDonorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientidlabel)
                    .addComponent(PatientIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientnamelabel)
                    .addComponent(PatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientagelabel)
                    .addComponent(PatientAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientLocLabel)
                    .addComponent(PatientLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientContactNoLabel)
                    .addComponent(ContactNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientBloodTypeLabel)
                    .addComponent(PatientBloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientWeightLabel)
                    .addComponent(PatientWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrganNeededLabel)
                    .addComponent(OrganNeededTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrganSizeLabel)
                    .addComponent(OrganSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(MedicalCondLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(FindDonorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FindDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindDonorBtnActionPerformed
        Organ organ1 = new Organ();
        organ1.setOrganName("Kindney");
        organ1.setOrganLife(5);
        
        Organ organ2 = new Organ();
        organ1.setOrganName("Liver");
        organ1.setOrganLife(5);
        
        ArrayList<Organ> organlist = new ArrayList<>();
        
        Donor foundDonor = new Donor();
        foundDonor.setDonorId("D1");
        foundDonor.setDonorName("Apoorva");
        foundDonor.setBloodGroup("B+");
        foundDonor.setDonorAddress("San Fransico");
        foundDonor.setDonorAge(27);
        foundDonor.setDonorGender("F");
        foundDonor.setDonorPhoneNumber(12345678);
        foundDonor.setOrganDonateList(organlist);
       
        ArrayList<Donor> foundDonorList = new ArrayList<>();
        foundDonorList.add(foundDonor);
        
        DonorFoundJPanel donorFound = new DonorFoundJPanel(userProcessContainer,account, system,foundDonorList);
        userProcessContainer.add("DonorFoundJPanel",donorFound);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_FindDonorBtnActionPerformed

    private void PatientAgeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAgeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientAgeTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactNoTextField;
    private javax.swing.JButton FindDonorBtn;
    private javax.swing.JLabel MedicalCondLabel;
    private javax.swing.JLabel OrganNeededLabel;
    private javax.swing.JTextField OrganNeededTextField;
    private javax.swing.JLabel OrganSizeLabel;
    private javax.swing.JTextField OrganSizeTextField;
    private javax.swing.JTextArea OtherMedicalConditionTextArea;
    private javax.swing.JTextField PatientAgeTextField;
    private javax.swing.JLabel PatientBloodTypeLabel;
    private javax.swing.JTextField PatientBloodTypeTextField;
    private javax.swing.JTextField PatientIDTextField;
    private javax.swing.JLabel PatientLocLabel;
    private javax.swing.JTextField PatientLocTextField;
    private javax.swing.JTextField PatientNameField;
    private javax.swing.JLabel PatientWeightLabel;
    private javax.swing.JTextField PatientWeightTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patientContactNoLabel;
    private javax.swing.JLabel patientagelabel;
    private javax.swing.JLabel patientidlabel;
    private javax.swing.JLabel patientnamelabel;
    // End of variables declaration//GEN-END:variables
}
